"""add converted_score to scores (3.7.16)

Revision ID: 21cddd8e2a52
Revises: b3f3555df8eb
Create Date: 2026-08-03 23:31:19.776136

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21cddd8e2a52"
down_revision: str | None = "b3f3555df8eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scores",
        sa.Column(
            "converted_score",
            sa.Float(),
            nullable=True,
            comment="折算分（按折算规则换算，NULL=未折算）",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scores", "converted_score")
    # ### end Alembic commands ###
