"""sprint-3.7: 字段动态增删 — field_definitions 表 + 5 表 ext_json 列

Revision ID: b3f3555df8eb
Revises: 090a005a9f30
Create Date: 2026-08-03 14:11:18.551339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f3555df8eb'
down_revision: Union[str, None] = '090a005a9f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # field_definitions 建表（幂等：已存在则跳过，兼容此前半途执行留下的表）
    bind = op.get_bind()
    if not bind.dialect.has_table(bind, "field_definitions"):
        op.create_table(
            'field_definitions',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('entity_type', sa.String(length=30), nullable=False, comment='所属实体类型'),
            sa.Column('field_key', sa.String(length=50), nullable=False, comment='字段键（写入 ext_json）'),
            sa.Column('label', sa.String(length=100), nullable=False, comment='显示名称'),
            sa.Column('field_type', sa.String(length=20), nullable=True, comment='string/int/float/date/enum/select/bool'),
            sa.Column('options', sa.Text(), nullable=True, comment='enum/select 选项，JSON 数组'),
            sa.Column('required', sa.Boolean(), nullable=True),
            sa.Column('sort_order', sa.Integer(), nullable=True),
            sa.Column('is_system', sa.Boolean(), nullable=True, comment='系统字段不可删除'),
            sa.Column('created_by', sa.String(length=50), nullable=True),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('entity_type', 'field_key', name='uq_field_definition'),
        )
        op.create_index('ix_field_definitions_entity_type', 'field_definitions', ['entity_type'], unique=False)
    # ext_json 列（幂等：已存在则跳过）
    for tbl in ("classes", "exams", "scores", "students", "teachers"):
        cols = [c[1] for c in bind.execute(sa.text(f"PRAGMA table_info({tbl})"))]
        if "ext_json" not in cols:
            op.add_column(tbl, sa.Column('ext_json', sa.Text(), nullable=True, comment='自定义扩展字段（JSON 对象）'))
    # 注意：uq_student_code 由 init_db() 手动维护（学籍号唯一，业务依赖），不属于 alembic 管理，此处不删
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'ext_json')
    # 注意：uq_student_code 由 init_db() 手动维护，不在 alembic 管理中，回滚不重建
    op.drop_column('students', 'ext_json')
    op.drop_column('scores', 'ext_json')
    op.drop_column('exams', 'ext_json')
    op.drop_column('classes', 'ext_json')
    op.drop_index('ix_field_definitions_entity_type', table_name='field_definitions')
    op.drop_table('field_definitions')
    # ### end Alembic commands ###
